name: CI
on: [push, pull_request]

jobs:
  registries-and-schema:
    name: Registries & Schema Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dev deps
        run: |
          python -m pip install -U pip
          python -m pip install pytest pyyaml jsonschema
      - name: Run focused tests
        run: |
          pytest -q tests/registries tests/schemas
